# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21471ca806d6ab404d681027afedd8716ab3bf2180e5f399b97f6309c4dae1ec1e3b44b7c9344ff0d50c65d2364bc417c75e770eafd7dbf7479adf07b6ffd9f8

test:
  secret_key_base: 6286beaf5528012e74f8cb15b46457ab09fe7565cdc3c5ddc2d76cdcf2e4af0d2697f1f5ea790efd0362f6e83696eda9ba772cd0507353f74d291ba345e75e6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
